# Generated by Django 5.1.5 on 2025-01-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.IntegerField(default=0)),
                ('defender_card', models.IntegerField(blank=True, null=True)),
                ('winning_condition', models.CharField(choices=[('high', 'Higher number wins'), ('low', 'Lower number wins')], default='high', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
