# Generated by Django 5.0.3 on 2025-01-16 08:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_result', models.IntegerField(default=0, verbose_name='게임 결과')),
                ('attacker_chosen_card', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='공격자가 선택한 카드')),
                ('defender_chosen_card', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='방어자가 선택한 카드')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker_games', to='users.user', verbose_name='공격자')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_games', to='users.user', verbose_name='방어자')),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임들',
                'ordering': ['-id'],
            },
        ),
    ]
