# Generated by Django 5.1.5 on 2025-01-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.RemoveField(
            model_name='game',
            name='attacker_chosen_card',
        ),
        migrations.RemoveField(
            model_name='game',
            name='defender_chosen_card',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_result',
        ),
        migrations.AddField(
            model_name='game',
            name='attacker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='defender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
