# Generated by Django 5.1.5 on 2025-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winning_condition',
            field=models.CharField(choices=[('high', 'Higher number wins'), ('low', 'Lower number wins')], default='high', max_length=10),
        ),
    ]
