# Generated by Django 5.1.5 on 2025-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='winner',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player1',
            new_name='attacker',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2',
            new_name='defender',
        ),
        migrations.AddField(
            model_name='game',
            name='attacker_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='defender_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
